mysql_user               =  "webplatformuser"
mysql_database           =  "webplatform"
mysql_host               =  "webplatformmysql"
webplatform_namespace    =  "dev"
webplatform_image        =  "docker.fuchicorp.com/webplatform-dev:latest"
dns_endpoint_webplatform =  "dev.academy.fuchicorp.com"
